"""Build and freshness-check Gauss-Kronrod data from pinned Netlib sources."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURE_DIR = ROOT / "tests" / "fixtures" / "quadpack"
JSON_OUTPUT = FIXTURE_DIR / "gk-reference.json"
PYTHON_OUTPUT = ROOT / "src" / "jaxstro" / "quad" / "_gk_data.py"
RETRIEVED = "2026-07-15"
SOURCES = {
    15: ("dqk15.f", "471664a145516508ce6147f1a425d7d3d7f3afe50fd9584ffff020749f534276"),
    21: ("dqk21.f", "4f89799878f42504549e952bf999d5e80e5253096a77dfe074f6353a92cceed7"),
    31: ("dqk31.f", "72017e6f65cd3ee9b49ed067962fd0254d077fa735821929aa46cdba30b75e9d"),
    41: ("dqk41.f", "3cc35dfb473cd7ccd7525307a698bfab99f4e3c509f541fa7afe706e80e92489"),
    51: ("dqk51.f", "a0ff6ad1b7cf30a4454494ed9fc1eddfefdb8fa12e8f0d8c173444616b13b55c"),
    61: ("dqk61.f", "39decfe58e8892e38e58827335306b0ebbf04d6fb4d701f68edbac8857ee0f72"),
}
DATA_PATTERN = re.compile(
    r"^\s*data\s+(wgk|xgk|wg)\s*\(\s*(\d+)\s*\)\s*/\s*(.*?)\s*/\s*$",
    re.IGNORECASE,
)


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _normalized_number(source: str) -> str:
    return "".join(source.split()).lower().replace("d", "e")


def _parse_source(pair: int, filename: str, expected_digest: str) -> dict:
    path = FIXTURE_DIR / filename
    observed_digest = _digest(path)
    if observed_digest != expected_digest:
        raise RuntimeError(
            f"{filename} SHA-256 mismatch: {observed_digest} != {expected_digest}"
        )
    arrays: dict[str, dict[int, str]] = {"wg": {}, "xgk": {}, "wgk": {}}
    for line in path.read_text(encoding="ascii").splitlines():
        match = DATA_PATTERN.match(line)
        if match is None:
            continue
        name, raw_index, raw_value = match.groups()
        arrays[name.lower()][int(raw_index)] = _normalized_number(raw_value)
    parsed = {
        name: [entries[index] for index in range(1, len(entries) + 1)]
        for name, entries in arrays.items()
    }
    if len(parsed["xgk"]) != (pair + 1) // 2:
        raise RuntimeError(f"{filename} has an unexpected xgk table length")
    if len(parsed["wgk"]) != len(parsed["xgk"]):
        raise RuntimeError(f"{filename} has mismatched xgk and wgk tables")
    if len(parsed["wg"]) != (pair - 1) // 4 + ((pair - 1) % 4 != 0):
        raise RuntimeError(f"{filename} has an unexpected wg table length")
    return {
        "pair": pair,
        "source": f"https://www.netlib.org/quadpack/{filename}",
        "retrieved": RETRIEVED,
        "sha256": expected_digest,
        **parsed,
    }


def _reference() -> dict:
    return {
        "schema_version": 1,
        "description": "Netlib provenance fixture; analytic moments are the numerical oracle.",
        "pairs": {
            str(pair): _parse_source(pair, filename, digest)
            for pair, (filename, digest) in SOURCES.items()
        },
    }


def _json_text(reference: dict) -> str:
    return json.dumps(reference, indent=2, sort_keys=True) + "\n"


def _python_text(reference: dict) -> str:
    lines = [
        '"""Generated Netlib Gauss-Kronrod positive-half tables."""',
        "",
        "# Generated by scripts/build_quadpack_gk_fixture.py; do not edit.",
        "",
        "GK_POSITIVE_DATA = {",
    ]
    for pair_text, entry in sorted(
        reference["pairs"].items(), key=lambda item: int(item[0])
    ):
        lines.append(f"    {pair_text}: {{")
        for name in ("xgk", "wgk", "wg"):
            lines.append(f'        "{name}": (')
            lines.extend(f"            {value}," for value in entry[name])
            lines.append("        ),")
        lines.append("    },")
    lines.extend(["}", "", '__all__ = ["GK_POSITIVE_DATA"]', ""])
    return "\n".join(lines)


def _check_or_emit(path: Path, expected: str, *, emit: bool) -> None:
    if emit:
        path.write_text(expected, encoding="utf-8")
        return
    observed = path.read_text(encoding="utf-8") if path.exists() else None
    if observed != expected:
        label = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
        raise RuntimeError(f"stale generated fixture: {label}")


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--emit", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    reference = _reference()
    _check_or_emit(JSON_OUTPUT, _json_text(reference), emit=args.emit)
    _check_or_emit(PYTHON_OUTPUT, _python_text(reference), emit=args.emit)


if __name__ == "__main__":
    main()
